// Canonical starter workflow template seed data (Phase 44).
// Conforms to WorkflowTemplate shape from types.ts.
// gate values are strings; defaultInstances are {_key, name} objects.

import type { WorkflowTemplate } from "./types";

// ===== Full-service residential =====
// 7 phases, 26 milestones

export const SEED_FULL_SERVICE_RESIDENTIAL: WorkflowTemplate = {
  _id: "wt-full-service-residential",
  _type: "workflowTemplate",
  name: "Full-service residential",
  version: 1,
  defaults: { clientApprovalDays: 10, dormancyDays: 60, revisionRounds: 1 },
  phases: [
    {
      _key: "ph-onboarding",
      id: "ph_onboarding",
      name: "Onboarding",
      order: 0,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-agreement",
          id: "ms_agreement",
          name: "Engagement agreement",
          assignee: "client",
          gate: "signature",
          optional: false,
          multiInstance: false,
          hardPrereqs: [],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-retainer-paid",
          id: "ms_retainer_paid",
          name: "Retainer paid",
          assignee: "client",
          gate: "payment",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_agreement"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-design-development",
      id: "ph_design_development",
      name: "Design development",
      order: 1,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-site-inspection",
          id: "ms_site_inspection",
          name: "Site photos, inspection & measurements",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_retainer_paid"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-foundation-meeting",
          id: "ms_foundation_meeting",
          name: "Foundation meeting",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_site_inspection"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-create-floorplan",
          id: "ms_create_floorplan",
          name: "Create floorplan",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_foundation_meeting"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-broad-concept",
          id: "ms_broad_concept",
          name: "Broad concept (few targeted options)",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_create_floorplan"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-presentation-1",
          id: "ms_presentation_1",
          name: "Client presentation",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_broad_concept"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-client-selects-option",
          id: "ms_client_selects_option",
          name: "Client selects option",
          assignee: "client",
          gate: "approval",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_presentation_1"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-full-concept",
          id: "ms_full_concept",
          name: "Full concept created",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_client_selects_option"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-presentation-2",
          id: "ms_presentation_2",
          name: "Client presentation",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_full_concept"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-single-revision",
          id: "ms_single_revision",
          name: "Single revision",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_presentation_2"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-presentation-3",
          id: "ms_presentation_3",
          name: "Client presentation",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_single_revision"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-additional-revision",
          id: "ms_additional_revision",
          name: "Additional revision",
          assignee: "designer",
          gate: null,
          optional: true,
          multiInstance: false,
          hardPrereqs: ["ms_presentation_3"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-final-concept",
          id: "ms_final_concept",
          name: "Final concept with contract",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_presentation_3"],
          softPrereqs: ["ms_additional_revision"],
          defaultInstances: [],
        },
        {
          _key: "ms-signed-proposal",
          id: "ms_signed_proposal",
          name: "Signed proposal",
          assignee: "client",
          gate: "signature",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_final_concept"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-trade-coordination",
      id: "ph_trade_coordination",
      name: "Trade coordination",
      order: 2,
      execution: "sequential",
      canOverlapWith: ["ph_procurement"],
      milestones: [
        {
          _key: "ms-trade-measuring",
          id: "ms_trade_measuring",
          name: "Site measuring",
          assignee: "trade",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: ["ms_signed_proposal"],
          softPrereqs: [],
          defaultInstances: [
            { _key: "di-carpet-installer", name: "Carpet installer" },
            { _key: "di-electrician", name: "Electrician" },
            { _key: "di-painter", name: "Painter" },
          ],
        },
        {
          _key: "ms-trade-quote",
          id: "ms_trade_quote",
          name: "Quote & scheduling",
          assignee: "trade",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: ["ms_trade_measuring"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-trade-contract",
          id: "ms_trade_contract",
          name: "Trade contract",
          assignee: "client",
          gate: "approval",
          optional: false,
          multiInstance: true,
          hardPrereqs: ["ms_trade_quote"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-trade-perform",
          id: "ms_trade_perform",
          name: "Performing the job",
          assignee: "trade",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: ["ms_trade_contract"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-procurement",
      id: "ph_procurement",
      name: "Project management & procurement",
      order: 3,
      execution: "parallel",
      canOverlapWith: ["ph_trade_coordination"],
      milestones: [
        {
          _key: "ms-merchandise-payment",
          id: "ms_merchandise_payment",
          name: "Merchandise payment",
          assignee: "client",
          gate: "payment",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_signed_proposal"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-ordering",
          id: "ms_ordering",
          name: "Ordering",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_merchandise_payment"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-tracking-delivery",
          id: "ms_tracking_delivery",
          name: "Tracking & delivery",
          assignee: "vendor",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_ordering"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-installation",
      id: "ph_installation",
      name: "Installation",
      order: 4,
      execution: "parallel",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-installation",
          id: "ms_installation",
          name: "Installation",
          assignee: "vendor",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: ["ms_tracking_delivery", "ms_trade_perform"],
          softPrereqs: [],
          defaultInstances: [
            { _key: "di-furniture-delivery", name: "Furniture delivery" },
            { _key: "di-carpet-install", name: "Carpet install" },
            { _key: "di-window-treatments", name: "Window treatments" },
            { _key: "di-lighting", name: "Lighting" },
          ],
        },
        {
          _key: "ms-styling",
          id: "ms_styling",
          name: "Styling",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_installation"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-walkthrough",
      id: "ph_walkthrough",
      name: "Walkthrough",
      order: 5,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-final-walkthrough",
          id: "ms_final_walkthrough",
          name: "Final walkthrough",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_styling"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-photography",
      id: "ph_photography",
      name: "Photography",
      order: 6,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-photography",
          id: "ms_photography",
          name: "Photography session",
          assignee: "designer",
          gate: null,
          optional: true,
          multiInstance: false,
          hardPrereqs: ["ms_final_walkthrough"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
  ],
};

// ===== Design consultation =====
// 3 phases, 8 milestones

export const SEED_DESIGN_CONSULTATION: WorkflowTemplate = {
  _id: "wt-design-consultation",
  _type: "workflowTemplate",
  name: "Design consultation",
  version: 1,
  defaults: { clientApprovalDays: 10, dormancyDays: 30, revisionRounds: 0 },
  phases: [
    {
      _key: "ph-consult-onboarding",
      id: "ph_consult_onboarding",
      name: "Onboarding",
      order: 0,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-consult-agreement",
          id: "ms_consult_agreement",
          name: "Engagement agreement",
          assignee: "client",
          gate: "signature",
          optional: false,
          multiInstance: false,
          hardPrereqs: [],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-consult-fee",
          id: "ms_consult_fee",
          name: "Consultation fee",
          assignee: "client",
          gate: "payment",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_consult_agreement"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-consultation",
      id: "ph_consultation",
      name: "Consultation",
      order: 1,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-consult-site-visit",
          id: "ms_consult_site_visit",
          name: "Site visit",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_consult_fee"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-consult-direction",
          id: "ms_consult_direction",
          name: "Design direction",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_consult_site_visit"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-consult-shopping-list",
          id: "ms_consult_shopping_list",
          name: "Shopping list",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_consult_direction"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-consult-presentation",
          id: "ms_consult_presentation",
          name: "Client presentation",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_consult_shopping_list"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-consult-followup",
      id: "ph_consult_followup",
      name: "Follow-up",
      order: 2,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-consult-followup-call",
          id: "ms_consult_followup_call",
          name: "Follow-up call",
          assignee: "designer",
          gate: null,
          optional: true,
          multiInstance: false,
          hardPrereqs: ["ms_consult_presentation"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-consult-upsell",
          id: "ms_consult_upsell",
          name: "Upsell to full-service",
          assignee: "designer",
          gate: null,
          optional: true,
          multiInstance: false,
          hardPrereqs: ["ms_consult_followup_call"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
  ],
};

// ===== Staging =====
// 5 phases, 11 milestones

export const SEED_STAGING: WorkflowTemplate = {
  _id: "wt-staging",
  _type: "workflowTemplate",
  name: "Staging",
  version: 1,
  defaults: { clientApprovalDays: 5, dormancyDays: 90, revisionRounds: 0 },
  phases: [
    {
      _key: "ph-staging-onboarding",
      id: "ph_staging_onboarding",
      name: "Onboarding",
      order: 0,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-staging-agreement",
          id: "ms_staging_agreement",
          name: "Engagement agreement",
          assignee: "client",
          gate: "signature",
          optional: false,
          multiInstance: false,
          hardPrereqs: [],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-staging-deposit",
          id: "ms_staging_deposit",
          name: "Deposit paid",
          assignee: "client",
          gate: "payment",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_staging_agreement"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-staging-preparation",
      id: "ph_staging_preparation",
      name: "Preparation",
      order: 1,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-staging-site-walk",
          id: "ms_staging_site_walk",
          name: "Site walk & measurements",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_staging_deposit"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-staging-inventory",
          id: "ms_staging_inventory",
          name: "Inventory selection",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_staging_site_walk"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-staging-staging",
      id: "ph_staging_staging",
      name: "Staging",
      order: 2,
      execution: "parallel",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-staging-delivery",
          id: "ms_staging_delivery",
          name: "Delivery & placement",
          assignee: "vendor",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: ["ms_staging_inventory"],
          softPrereqs: [],
          defaultInstances: [
            { _key: "di-staging-furniture-rental", name: "Furniture rental" },
            { _key: "di-staging-art-accessories", name: "Art & accessories" },
          ],
        },
        {
          _key: "ms-staging-styling",
          id: "ms_staging_styling",
          name: "Styling",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_staging_delivery"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-staging-photography",
      id: "ph_staging_photography",
      name: "Photography",
      order: 3,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-staging-photography",
          id: "ms_staging_photography",
          name: "Photography session",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_staging_styling"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "ph-destaging",
      id: "ph_destaging",
      name: "De-staging",
      order: 4,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-staging-property-sold",
          id: "ms_staging_property_sold",
          name: "Property sold trigger",
          assignee: "client",
          gate: "approval",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ms_staging_photography"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-staging-pickup",
          id: "ms_staging_pickup",
          name: "Furniture pickup",
          assignee: "vendor",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: ["ms_staging_property_sold"],
          softPrereqs: [],
          defaultInstances: [
            { _key: "di-pickup-furniture-rental", name: "Furniture rental" },
            { _key: "di-pickup-art-accessories", name: "Art & accessories" },
          ],
        },
      ],
    },
  ],
};

export const ALL_SEEDS: WorkflowTemplate[] = [
  SEED_FULL_SERVICE_RESIDENTIAL,
  SEED_DESIGN_CONSULTATION,
  SEED_STAGING,
];
