// Starter workflow template seed data (spec §5 and §6).
// These are plain TypeScript data objects — no runtime logic.
// POSTed idempotently by the seed endpoint in Plan 04.
// Conforms to WorkflowTemplate shape from types.ts.

import type { WorkflowTemplate } from "./types";

const DEFAULTS = { clientApprovalDays: 10, dormancyDays: 60, revisionRounds: 1 } as const;

// ===== Full-service residential (spec §5) =====
// 6 phases, 24+ milestones

export const SEED_FULL_SERVICE_RESIDENTIAL: WorkflowTemplate = {
  _id: "wt-full-service-residential",
  _type: "workflowTemplate",
  name: "Full-service residential",
  version: 1,
  defaults: { ...DEFAULTS },
  phases: [
    {
      _key: "phase-onboarding",
      id: "onboarding",
      name: "Onboarding",
      order: 0,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-agreement",
          id: "agreement",
          name: "Agreement",
          assignee: "client",
          gate: "signature",
          optional: false,
          multiInstance: false,
          hardPrereqs: [],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-retainer-paid",
          id: "retainer-paid",
          name: "Retainer paid",
          assignee: "client",
          gate: "payment",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["agreement"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "phase-design-development",
      id: "design-development",
      name: "Design development",
      order: 1,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-site-photos",
          id: "site-photos-inspection-measurements",
          name: "Site photos, inspection & measurements",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["retainer-paid"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-foundation-meeting",
          id: "foundation-meeting",
          name: "Foundation meeting",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["site-photos-inspection-measurements"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-create-floorplan",
          id: "create-floorplan",
          name: "Create floorplan",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["foundation-meeting"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-broad-concept",
          id: "broad-concept",
          name: "Broad concept (few targeted options)",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["create-floorplan"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-presentation-concept",
          id: "presentation-concept",
          name: "Presentation to client",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["broad-concept"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-client-selects-option",
          id: "client-selects-option",
          name: "Client selects option",
          assignee: "client",
          gate: "approval",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["presentation-concept"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-full-concept",
          id: "full-concept",
          name: "Full concept created",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["client-selects-option"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-presentation-full",
          id: "presentation-full",
          name: "Presentation to client",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["full-concept"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-single-revision",
          id: "single-revision",
          name: "Single revision",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["presentation-full"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-presentation-revised",
          id: "presentation-revised",
          name: "Presentation to client",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["single-revision"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-additional-revision",
          id: "additional-revision",
          name: "Additional revision",
          assignee: "designer",
          gate: null,
          optional: true,
          multiInstance: false,
          hardPrereqs: ["presentation-revised"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-final-concept",
          id: "final-concept",
          name: "Final concept with contract",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["presentation-revised"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-signed-proposal",
          id: "signed-proposal",
          name: "Signed proposal",
          assignee: "client",
          gate: "signature",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["final-concept"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "phase-trade-coordination",
      id: "trade-coordination",
      name: "Trade coordination",
      order: 2,
      execution: "sequential",
      canOverlapWith: ["project-management-procurement"],
      milestones: [
        {
          _key: "ms-site-measuring",
          id: "site-measuring",
          name: "Site measuring",
          assignee: "trade",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: [],
          softPrereqs: [],
          defaultInstances: [
            { _key: "di-carpet-installer", name: "Carpet installer" },
            { _key: "di-electrician", name: "Electrician" },
            { _key: "di-painter", name: "Painter" },
          ],
        },
        {
          _key: "ms-quote-scheduling",
          id: "quote-scheduling",
          name: "Quote & scheduling",
          assignee: "trade",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: ["site-measuring"],
          softPrereqs: [],
          defaultInstances: [
            { _key: "di-qs-carpet-installer", name: "Carpet installer" },
            { _key: "di-qs-electrician", name: "Electrician" },
            { _key: "di-qs-painter", name: "Painter" },
          ],
        },
        {
          _key: "ms-trade-contract",
          id: "trade-contract",
          name: "Trade contract",
          assignee: "client",
          gate: "approval",
          optional: false,
          multiInstance: true,
          hardPrereqs: ["quote-scheduling"],
          softPrereqs: [],
          defaultInstances: [
            { _key: "di-tc-carpet-installer", name: "Carpet installer" },
            { _key: "di-tc-electrician", name: "Electrician" },
            { _key: "di-tc-painter", name: "Painter" },
          ],
        },
        {
          _key: "ms-performing-job",
          id: "performing-job",
          name: "Performing the job",
          assignee: "trade",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: ["trade-contract"],
          softPrereqs: [],
          defaultInstances: [
            { _key: "di-pj-carpet-installer", name: "Carpet installer" },
            { _key: "di-pj-electrician", name: "Electrician" },
            { _key: "di-pj-painter", name: "Painter" },
          ],
        },
      ],
    },
    {
      _key: "phase-project-management-procurement",
      id: "project-management-procurement",
      name: "Project management & procurement",
      order: 3,
      execution: "parallel",
      canOverlapWith: ["trade-coordination"],
      milestones: [
        {
          _key: "ms-merchandise-payment",
          id: "merchandise-payment",
          name: "Merchandise payment",
          assignee: "client",
          gate: "payment",
          optional: false,
          multiInstance: false,
          hardPrereqs: [],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-ordering",
          id: "ordering",
          name: "Ordering",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["merchandise-payment"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-tracking-delivery",
          id: "tracking-delivery",
          name: "Tracking & delivery",
          assignee: "vendor",
          gate: "delivery",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["ordering"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "phase-installation",
      id: "installation",
      name: "Installation",
      order: 4,
      execution: "parallel",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-installation",
          id: "installation",
          name: "Installation",
          assignee: "vendor",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: [],
          softPrereqs: [],
          defaultInstances: [
            { _key: "di-furniture-delivery", name: "Furniture delivery" },
            { _key: "di-carpet-install", name: "Carpet install" },
            { _key: "di-window-treatments", name: "Window treatments" },
            { _key: "di-lighting", name: "Lighting" },
          ],
        },
        {
          _key: "ms-styling",
          id: "styling",
          name: "Styling",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["installation"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "phase-walkthrough-closeout",
      id: "walkthrough-closeout",
      name: "Walkthrough & closeout",
      order: 5,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-final-walkthrough",
          id: "final-walkthrough",
          name: "Final walkthrough",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["styling"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-photography-session",
          id: "photography-session",
          name: "Photography session",
          assignee: "designer",
          gate: null,
          optional: true,
          multiInstance: false,
          hardPrereqs: ["final-walkthrough"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
  ],
};

// ===== Design consultation (spec §6) =====
// 3 phases, 8 milestones total

export const SEED_DESIGN_CONSULTATION: WorkflowTemplate = {
  _id: "wt-design-consultation",
  _type: "workflowTemplate",
  name: "Design consultation",
  version: 1,
  defaults: { ...DEFAULTS },
  phases: [
    {
      _key: "phase-dc-onboarding",
      id: "dc-onboarding",
      name: "Onboarding",
      order: 0,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-dc-agreement",
          id: "dc-agreement",
          name: "Agreement",
          assignee: "client",
          gate: "signature",
          optional: false,
          multiInstance: false,
          hardPrereqs: [],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-dc-consultation-fee",
          id: "dc-consultation-fee",
          name: "Consultation fee paid",
          assignee: "client",
          gate: "payment",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["dc-agreement"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "phase-dc-consultation",
      id: "dc-consultation",
      name: "Consultation",
      order: 1,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-dc-site-visit",
          id: "dc-site-visit",
          name: "Site visit & assessment",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["dc-consultation-fee"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-dc-design-direction",
          id: "dc-design-direction",
          name: "Design direction document",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["dc-site-visit"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-dc-shopping-list",
          id: "dc-shopping-list",
          name: "Shopping & resource list",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["dc-design-direction"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-dc-presentation",
          id: "dc-presentation",
          name: "Presentation to client",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["dc-shopping-list"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "phase-dc-followup",
      id: "dc-followup",
      name: "Follow-up",
      order: 2,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-dc-followup-call",
          id: "dc-followup-call",
          name: "Follow-up call",
          assignee: "designer",
          gate: null,
          optional: true,
          multiInstance: false,
          hardPrereqs: ["dc-presentation"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-dc-upsell",
          id: "dc-upsell",
          name: "Upsell to full-service",
          assignee: "designer",
          gate: null,
          optional: true,
          multiInstance: false,
          hardPrereqs: ["dc-followup-call"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
  ],
};

// ===== Staging (spec §6) =====
// 5 phases, 10 milestones

export const SEED_STAGING: WorkflowTemplate = {
  _id: "wt-staging",
  _type: "workflowTemplate",
  name: "Staging",
  version: 1,
  defaults: { ...DEFAULTS },
  phases: [
    {
      _key: "phase-st-onboarding",
      id: "st-onboarding",
      name: "Onboarding",
      order: 0,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-st-agreement",
          id: "st-agreement",
          name: "Agreement",
          assignee: "client",
          gate: "signature",
          optional: false,
          multiInstance: false,
          hardPrereqs: [],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-st-deposit",
          id: "st-deposit",
          name: "Deposit paid",
          assignee: "client",
          gate: "payment",
          optional: false,
          multiInstance: false,
          hardPrereqs: ["st-agreement"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "phase-st-preparation",
      id: "st-preparation",
      name: "Preparation",
      order: 1,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-st-site-walk",
          id: "st-site-walk",
          name: "Site walk & measurements",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["st-deposit"],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-st-inventory-selection",
          id: "st-inventory-selection",
          name: "Inventory selection",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["st-site-walk"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "phase-st-staging",
      id: "st-staging",
      name: "Staging",
      order: 2,
      execution: "parallel",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-st-delivery-placement",
          id: "st-delivery-placement",
          name: "Delivery & placement",
          assignee: "vendor",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: ["st-inventory-selection"],
          softPrereqs: [],
          defaultInstances: [
            { _key: "di-st-furniture-rental", name: "Furniture rental" },
            { _key: "di-st-art-accessories", name: "Art & accessories" },
          ],
        },
        {
          _key: "ms-st-styling",
          id: "st-styling",
          name: "Styling",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["st-delivery-placement"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "phase-st-photography",
      id: "st-photography",
      name: "Photography",
      order: 3,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-st-photography-session",
          id: "st-photography-session",
          name: "Photography session",
          assignee: "designer",
          gate: null,
          optional: false,
          multiInstance: false,
          hardPrereqs: ["st-styling"],
          softPrereqs: [],
          defaultInstances: [],
        },
      ],
    },
    {
      _key: "phase-st-destaging",
      id: "st-destaging",
      name: "De-staging",
      order: 4,
      execution: "sequential",
      canOverlapWith: [],
      milestones: [
        {
          _key: "ms-st-property-sold",
          id: "st-property-sold",
          name: "Property sold trigger",
          assignee: "client",
          gate: "approval",
          optional: false,
          multiInstance: false,
          hardPrereqs: [],
          softPrereqs: [],
          defaultInstances: [],
        },
        {
          _key: "ms-st-furniture-pickup",
          id: "st-furniture-pickup",
          name: "Furniture pickup",
          assignee: "vendor",
          gate: null,
          optional: false,
          multiInstance: true,
          hardPrereqs: ["st-property-sold"],
          softPrereqs: [],
          defaultInstances: [
            { _key: "di-fp-furniture-rental", name: "Furniture rental" },
            { _key: "di-fp-art-accessories", name: "Art & accessories" },
          ],
        },
      ],
    },
  ],
};

export const ALL_SEEDS: WorkflowTemplate[] = [
  SEED_FULL_SERVICE_RESIDENTIAL,
  SEED_DESIGN_CONSULTATION,
  SEED_STAGING,
];
