// scripts/generate-theme-css.ts
//
// Phase 45 Plan 02 -- generates src/styles/_generated-theme.css from
// src/lib/brand-tokens.ts. Tailwind v4 reads the generated file via an
// @import in src/styles/global.css.
//
// D-05: src/lib/brand-tokens.ts is the source of truth.
// D-08: The generated file IS committed; CI verifies
//   `git diff --exit-code src/styles/_generated-theme.css` is empty after
//   `npm run theme:gen`.
//
// Usage:
//   npm run theme:gen          (CLI; chained from prebuild + predev)
//   npx tsx scripts/generate-theme-css.ts
//
// Exported API (for tests):
//   buildThemeCss(tokens: BrandTokens) -> string
//     Pure function -- returns the CSS body without any file-write side effect
//     so the round-trip Vitest in src/lib/brand-tokens.test.ts can call it.

import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { brandTokens, type BrandTokens } from "../src/lib/brand-tokens.ts";

const HEADER = `/* AUTO-GENERATED by scripts/generate-theme-css.ts. Do not edit by hand.
   Source of truth: src/lib/brand-tokens.ts. Run \`npm run theme:gen\` to regenerate. */`;

function kebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

export function buildThemeCss(tokens: BrandTokens): string {
  const lines: string[] = [HEADER, "", "@theme {", "  /* Color palette */"];
  for (const [name, value] of Object.entries(tokens.colors)) {
    lines.push(`  --color-${kebab(name)}: ${value};`);
  }
  lines.push("", "  /* Typography */");
  for (const [name, value] of Object.entries(tokens.fonts)) {
    lines.push(`  --font-${kebab(name)}: ${value};`);
  }
  lines.push("", "  /* Spacing scale */");
  for (const [name, value] of Object.entries(tokens.spacing)) {
    lines.push(`  --spacing-${kebab(name)}: ${value};`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

// CLI entry -- only runs when invoked directly (npm run theme:gen).
// Use realpathSync-style fileURL comparison via fileURLToPath to handle the
// `tsx` loader's argv shape.
const invokedDirectly = (() => {
  try {
    return import.meta.url === `file://${process.argv[1]}`;
  } catch {
    return false;
  }
})();

if (invokedDirectly) {
  const here = path.dirname(fileURLToPath(import.meta.url));
  const outPath = path.resolve(here, "../src/styles/_generated-theme.css");
  writeFileSync(outPath, buildThemeCss(brandTokens), "utf8");
  const counts =
    `${Object.keys(brandTokens.colors).length} colors, ` +
    `${Object.keys(brandTokens.fonts).length} fonts, ` +
    `${Object.keys(brandTokens.spacing).length} spacing tokens`;
  // biome-ignore lint/suspicious/noConsole: CLI script logs progress to stdout.
  console.log(`Wrote ${outPath} (${counts})`);
}
